baseurl: ""
url: ""
logo: logo.svg

languages: ["ru"]
exclude_from_localizations: ["js", "images", "assets"]
default_locale_in_subfolder: false

markdown: kramdown
permalink: /posts/:categories/:year/:month/:day/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tagging
  - jekyll-multiple-languages-plugin

paginate: 1
paginate_path: "/page/:num"

include:
  - _pages

tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
